export interface IScopeOfWork {
  id?: string;
  description: string;
  isSelected: boolean;
  details: string;
  // newConstruction: boolean;
  // newConstructionDetail: string;
  // erection: boolean;
  // erectionDetail: string;
  // addition: boolean;
  // additionDetail: string;
  // alteration: boolean;
  // alterationDetail: string;
  // renovation: boolean;
  // renovationDetail: string;
  // convertion: boolean;
  // convertionDetail: string;
  // repair: boolean;
  // repairDetail: string;
  // moving: boolean;
  // movingDetail: string;
  // raising: boolean;
  // raisingDetail: string;
  // accessoryBuildingOrStruc: boolean;
  // accessoryBuildingOrStrucDetail: string;
  // legalization: boolean;
  // legalizationDetail: string;
  // other: boolean;
  // otherDetail: string;
}
